### ISSUE TITLE
Warning 39 raised by (at least) ord

### ISSUE THREAD

**Issue by thizanne** [whitequark/ppx_deriving#104]
Deriving ord (and possibly other plugins ?) raises warning 39 (unused rec flag) when used on a non-recursive type. Below is a minimal example.

```ocaml
(* test.ml *)
type t = A [@@deriving ord]
```

```console
$ ocamlfind ocamlc -c -package ppx_deriving.std -w +39 test.ml
File "test.ml", line 1, characters 0-27:
Warning 39: unused rec flag.
```

**Comment by whitequark** [comment]
Yep, this is a known behavior. I will accept a PR fixing it.

**Comment by whitequark** [comment]
Closing as I have no time to fix minor issues like that.
