### ISSUE TITLE
Add hooks for ppx_sexp_conv

### ISSUE THREAD

**Issue by rgrinberg** [whitequark/ppx_deriving#108]
@whitequark Would you accept the hooks described by diml here:

https://github.com/janestreet/ppx_type_conv/issues/6#issuecomment-236841566

If so, then I'll give implementing them a shot.

**Comment by whitequark** [comment]
Sure.

**Comment by whitequark** [comment]
Fixed in #109.

**Comment by prepor** [comment]
Hello. Are you going to release this?

**Comment by whitequark** [comment]
Will do over the weekend

**Comment by whitequark** [comment]
https://github.com/ocaml/opam-repository/pull/7505
