### ISSUE TITLE
Is there any method to configure the `show` deriving print effect?

### ISSUE THREAD

**Issue by qdwang** [whitequark/ppx_deriving#112]
Like indentation or something.

**Comment by whitequark** [comment]
No.

**Comment by qdwang** [comment]
@whitequark It seems that the string generated by `show` has a line length limited to 80 columns. But the  `$COLUMN` is set to 200. How can this limitation be changed?

**Comment by whitequark** [comment]
The `show` deriver uses the OCaml [Format](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Format.html) module. I believe you can use the generated `pp_*` functions with a formatter you provide, and use `Format.pp_set_margin` to configure wrap width.

**Comment by qdwang** [comment]
@whitequark works, thanks.
