### ISSUE TITLE
How to deriving OCaml inner type like `Lexing.position`?

### ISSUE THREAD

**Issue by qdwang** [whitequark/ppx_deriving#113]
```
type pos = Lexing.position
[@@deriving show]
```

In the way, it will still cause the `Error: Unbound value Lexing.pp_position`

**Comment by whitequark** [comment]
https://github.com/whitequark/ppx_import/#combining-with-deriving

**Comment by qdwang** [comment]
When using yojson, it shows `yojson cannot be derived for [%import :Lexing.position]`

**Comment by whitequark** [comment]
> Note that you need to require import before any deriving plugins, as otherwise deriving will not be able to observe the complete type.

**Comment by qdwang** [comment]
Thanks
