### ISSUE TITLE
PPX rewritten output recursively parsed ?

### ISSUE THREAD

**Issue by xguerin** [whitequark/ppx_deriving#117]
Hello there,

I wrote a plugin that basically does the following, from:

```ocaml
module S = struct
  type 'a t =
    {
      a : 'a [@bits 2];
      b : 'a [@bits 2];
    }[@@deriving hardcaml]
end
```

To, using `ocamlfind ocamlc -dsource ...`:

```ocaml
module S =
  struct
    type 'a t = {
      a: 'a [@bits 2];
      b: 'a [@bits 2]}[@@deriving hardcaml]
    let rec t = { a = ("a", 2); b = ("b", 2) }
    
    and map f x = { a = (f x.a); b = (f x.b) }
    
    and map2 f x0 x1 = { a = (f x0.a x1.a); b = (f x0.b x1.b) }
    
    and to_list x = List.concat [[x.a]; [x.b]]
    
  end
```

The output looks fine to me, especially compared to the `map` plugin. However, when compiling the file I am getting the following error:

```
$ ocamlfind ocamlc -package ppx_deriving_hardcaml test.ml 
File "test.ml", line 2, characters 2-94:
Error: Unbound module x
```

`x` begin the second argument to `map`, wrongly assumed to be a `module` in that case. If I edit the output of `-dsource`, remote `[@@deriving hardcaml]` and try to compile the file, I do not get the error anymore.

Is there a step that I am missing ? Just in case, the source is located here: https://github.com/xguerin/ppx_deriving_hardcaml.

Thanks,

**Comment by xguerin** [comment]
Please ignore that drivel. I was using `Ldot` instead of `Exp.field`. No type system in the world can efficiently prevent one from being a complete moron.

**Comment by whitequark** [comment]
Yes, that's what I was about to reply with. Don't beat yourself too much, OCaml's AST could use a validator.
