### ISSUE TITLE
4.05 support

### ISSUE THREAD

**Issue by copy** [whitequark/ppx_deriving#121]
On a clean 4.05.0+beta1 switch with `ppx_tools` pinned to the git repo:

`opam pin add ppx_tools --dev-repo https://github.com/alainfrisch/ppx_tools.git`

```
File "src/ppx_deriving.cppo.ml", line 313, characters 52-63:
Error: This expression has type string list
       but an expression was expected of type string Asttypes.loc list
       Type string is not compatible with type
         string Asttypes.loc = string Location.loc 
Command exited with code 2.
```

**Comment by hcarty** [comment]
https://github.com/let-def/ocaml-migrate-parsetree could be useful to smooth over AST changes and avoid the current `cppo` pre-processing.

**Comment by whitequark** [comment]
A pull request is welcome.

**Comment by hcarty** [comment]
In case I or someone else gets a chance to work on this later - an article for converting a ppx to ocaml-migrate-parsetree: http://ocamllabs.io/projects/2017/02/15/ocaml-migrate-parsetree.html

**Comment by gasche** [comment]
A port to ocaml-migrate-parsetree is discussed in https://github.com/whitequark/ppx_deriving/pull/123 .

**Comment by whitequark** [comment]
Fixed in master.

**Comment by gasche** [comment]
It would be nice if you could have a release soon; 4.05 should be out soon (the "six month" goal was on April 4, but the released will be delayed a bit).

**Comment by aantron** [comment]
I second requesting a release.

**Comment by aantron** [comment]
I see "damiendoligez created tag 4.05.0+rc1 at ocaml/ocaml  35 minutes ago" in my GH feed. Any update on releasing ppx_deriving?

**Comment by fpottier** [comment]
+1! I have a package that depends on ppx_deriving and would like to test it with 4.05rc1. I expect many others are in the same situation.

**Comment by whitequark** [comment]
Alright everyone,

I know this is really overdue and I'm sorry. I've been having health issues and for a few months I could not really dedicate much time to OSS. That has now ended and I'll merge 4.05 support ASAP.
