### ISSUE TITLE
Please, add to README how to load ppx_deriving with some plugin to `ppx_tools/rewriter`.

### ISSUE THREAD

**Issue by Kakadu** [whitequark/ppx_deriving#125]
I have some troubles realizing this on my own.

**Comment by whitequark** [comment]
Pending https://github.com/whitequark/ppx_deriving/pull/123 there will be a change anyway. Maybe ask @let-def how to use it with the new system?

**Comment by Kakadu** [comment]
So, if I'm developing a new plugin I should rely on Frederic's fork?

**Comment by whitequark** [comment]
It seems the way forward, yes.

**Comment by whitequark** [comment]
@let-def Can you elaborate on how manually rewriting some source is supposed to be done now?

**Comment by let-def** [comment]
If invoked without `--as-ppx`, `ppx_deriving` binary does the rewriting on stdout.

The problem is to provide the path to ppx_deriving plugins, for instance this should do:
```shell
ocamlfind ppx_deriving/ppx_deriving -deriving-plugin `ocamlfind query ppx_deriving`/ppx_deriving_show.cma test.ml
```

**Comment by mseri** [comment]
Is it possible to use ppx_deriving with jbuilder with your changes?

**Comment by let-def** [comment]
Yes, we worked with that in mind with @diml .

**Comment by whitequark** [comment]
README updated.
