### ISSUE TITLE
When used as a command line tool, ppx_deriving will translate ## as a infix operator

### ISSUE THREAD

**Issue by dorafmon** [whitequark/ppx_deriving#129]
Eg. `obj##foo` will be translated to `(## obj foo)` when I invoke `ppx_deriving` as a command line tool (compiled by myself). I understand `##` is not standard object dispatch, but is it possible that we keep it as it is, and not transform it?

Thanks!

Best,
Bob

**Comment by whitequark** [comment]
ppx_deriving does not perform this transformation, parsetree printers do. Please report a bug against OCaml and/or the ocaml-migrate-parsetree project instead. (The latter is what ppx_deriving currently uses but they probably want to stay consistent with OCaml.)
