### ISSUE TITLE
deriving first-class variant constructors/field accessor

### ISSUE THREAD

**Issue by c-cube** [whitequark/ppx_deriving#14]
In a similar way to [variantslib](https://github.com/janestreet/variantslib) and [fieldslib](https://github.com/janestreet/fieldslib), be able to generate functions:

```ocaml
type foo =
  | A of int
  | B of string * foo
  [@@deriving variants];;

(* generated *)
val a : int -> foo
val b : string -> foo -> foo
```

and 

```ocaml
type space_point = {
  x : int;
  y : int;
  history : space_point list;
} [@@deriving fields];;

(* generated *)
val x : space_point -> int
val y : space_point -> int
val history : space_point -> space_point list
```

**Comment by rgrinberg** [comment]
@c-cube do you think this is still necessary as you can use jsc's ppx_fields_conv. Or do you find it deficient?

**Comment by whitequark** [comment]
Closing. Whoever needs this can implement this.
