### ISSUE TITLE
Build method without OPAM

### ISSUE THREAD

**Issue by camlspotter** [whitequark/ppx_deriving#16]
Could you detail how to build ppx_deriving without OPAM for ppl with OCaml on MinGW?

From `opam` file, it seems to be
```
$ sed -e 's/%{version}%/1.1/g' pkg/META.in > pkg/META
$ ocaml pkg/build.ml native=true native-dynlink=true
```

In my environment the above builds things fine. The hard part is the installation. I had to run `ocamlifind` manually getting the file information from `ppx_deriving.install`.

Thanks!

**Comment by modlfo** [comment]
I was able to compile ppx_deriving in the MSVC port of Ocaml with make. The only change that I had to do was to make was to change the ".a" extension to ".lib" in the pkg/topkg.ml file.

After building I had to manually fix the version in the META file and copy all the compiled files to my site-lib directory. Also I had to rename the ppx_deriving_main.native to ppx_deriving.exe

**Comment by whitequark** [comment]
I've been using a newer topkg version for a while that has better Windows support--could you please recheck? @modlfo @camlspotter

**Comment by modlfo** [comment]
There's still an issue installing in Windows. I get this error:
```
Installed C:\OCAMLM~1\lib\site-lib\ppx_deriving\META
mv `ocamlfind query ppx_deriving`/ppx_deriving_main.native `ocamlfind query ppx_deriving`/ppx_deriving.exe
mv: cannot stat ‘C:\\OCAMLM~1\\lib\\site-lib\\ppx_deriving\r/ppx_deriving_main.native’: No such file or directory
Makefile:52: recipe for target 'install' failed
make: *** [install] Error 1

```

there's an strange \r in the path name. I don't know if this happens only in my computer.

**Comment by whitequark** [comment]
@modlfo can you try again with the last command being...

    mv `ocamlfind query ppx_deriving -suffix /ppx_deriving_main.native` `ocamlfind query ppx_deriving -suffix /ppx_deriving$(EXE)`

?

**Comment by modlfo** [comment]
That las command works correctly. I get the ppx_deriving.exe in the library folder. Thanks!
