### ISSUE TITLE
Derive visitors

### ISSUE THREAD

**Issue by Drup** [whitequark/ppx_deriving#17]
I would like to be able to derive visitors, in the style of `Ast_mapper`.

Given a set of type in a `type ... and ...` declaration, a visitor would be a record with one field per type and a field for each external type used in the type declarations.

**Comment by rgrinberg** [comment]
What about class based visitors? Is there a need for those?

**Comment by Drup** [comment]
Frankly, I would argue that only class based visitors are useful. It's much much more convenient and the speed penalty is not that terrible. See ppx_core for examples of nice mappers.

**Comment by rgrinberg** [comment]
@Drup By the way, isn't this what you want? https://github.com/choeger/ppx_deriving_morphism It doesn't use classes but perhaps you can request that as a feature.

**Comment by Drup** [comment]
Indeed, this seems to be what I want, nice @choeger !

**Comment by choeger** [comment]
Thanks. Be aware that this tool is far from being mature, I mainly developed it to scratch my own itch. That being said, contributions of **any** form are of course welcome.  Btw, is there any real reason for class based visitors (except for the builtin recursion)? With the concise record syntax, I do not think one needs inheritance.

Version 0.2.0 should hit opam quite soon, btw.

**Comment by whitequark** [comment]
Closing. Whoever needs this can implement this.

**Comment by Wilfred** [comment]
Related: https://gitlab.inria.fr/fpottier/visitors
