### ISSUE TITLE
Assumption about List.map

### ISSUE THREAD

**Issue by smondet** [whitequark/ppx_deriving#28]
The generated code uses `List.map` and expects a particular order for its arguments which is not the one used in `Core_kernel` or [nonstd](http://seb.mondet.org/software/nonstd/index.html).

```ocaml

#require "ppx_deriving.show";;
type t = {x: string list} [@@deriving show];;
(*
type t = { x : bytes list; }
val pp : Format.formatter -> t -> unit = <fun>
val show : t -> bytes = <fun>
*)

module List = struct
  include ListLabels
  let map l ~f = map ~f l
end
type t = {x: string list} [@@deriving show];;
(*
Error: This expression should not be a function, the expected type is
'a list
*)
```

I recommend generating code that uses `ListLabels.map` directly, it's much less likely that anyone will override that name, and using labels will make much better error messages anyway.

Edit: comments, formatting and typos

**Comment by whitequark** [comment]
Not quite. The right way to fix this is to add Ppx_deriving_runtime, [like in ppx_deriving_yojson](https://github.com/whitequark/ppx_deriving_yojson/blob/master/src/ppx_deriving_yojson_runtime.ml#L13-L19).

**Comment by smondet** [comment]
Indeed much better in the long term.

**Comment by whitequark** [comment]
Fixed in https://github.com/whitequark/ppx_deriving/commit/b3dd8678a9179bba6fcbea5c4429867fd86ab2c3.
