### ISSUE TITLE
Improve locations for external functions

### ISSUE THREAD

**Issue by Drup** [whitequark/ppx_deriving#30]
For example:
```ocaml
type t = { 
  foo : Foo.t option
} [@@deriving show]
```
The generated identifier `Foo.to_string` could be located either to the `foo` field or to the `Foo.t` type. 
It would help with [big records](https://github.com/ocsigen/ocsigenserver/blob/cohttp_rebased/src/server/ocsigen_request_info.ml#L15-L83) (No, I didn't wrote this monstrosity).

**Comment by whitequark** [comment]
Good idea. This would be easy to fix using `[@metaloc]`, I think.

**Comment by Drup** [comment]
I plan to do it, just posting bugs so I don't forget while debugging something else.

**Comment by whitequark** [comment]
So, are you going to do it?

**Comment by Drup** [comment]
Apparently, I did forget ... I will try to make time, no guarantee. :(

**Comment by whitequark** [comment]
Closing. Whoever needs this can implement this.

**Comment by whitequark** [comment]
Oh, looks like this was fixed by @gasche  in 4fc257050.
