### ISSUE TITLE
Handle Lazy.t in show.

### ISSUE THREAD

**Issue by Drup** [whitequark/ppx_deriving#31]
The sensible handling would be to test if it's evaluated (with Lazy.is_val) and print it or `<not evaluated>`.

**Comment by Twinside** [comment]
Handling it for eq & ord could be beneficial, but it imply to force the thunk.

**Comment by whitequark** [comment]
Wish granted: https://github.com/whitequark/ppx_deriving/commit/483161259b3f219d6447abb2af03ebab145e027f.
