### ISSUE TITLE
Recursive application of the mapper

### ISSUE THREAD

**Issue by paurkedal** [whitequark/ppx_deriving#33]
I think there should be a way to apply the deriving-mapper to expression-valued attributes. Maybe as an alternative Arg.expr or by exposing the mapper as a global?

My motivation is that I wrote a [syntax extension to generate random instances of types](https://github.com/paurkedal/ppx_deriving_random).  The derived-from type takes an attribute `[@random ...]` to override with custom generator code, where I need reliable way to refer to generators for parameters or the type itself, e.g. in
```ocaml
type 'a term =
  | Var of 'a
  | App  [@weight 0.5] of 'a term * 'a term
  | Lam of ('a * 'a term) [@random random_lambda [%random: 'a term]]
  [@@deriving random]
```
In other cases `random_lambda` might use just `[%random: 'a]`.  The internal name `poly_a` is needed in either case, which makes me think the best way to refer to it is to use `[%random: ...]`.  I could systematically apply all parameter generators to the custom generator and use:
```ocaml
  | Lam of ('a * 'a term) [@random random_lambda random_term]
```
In my opinion, explicit arguments are nicer.

**Comment by whitequark** [comment]
Nice syntax extension!

I agree that the mapper should be exported. Would you make a PR?

**Comment by paurkedal** [comment]
Thanks!

Sure, though I can't think of a nice way to do it without breaking backwards compatibility.  If doing it from scratch I would have replaced the ~option ~path parameters with a single private record for extensibility.  To keep backwards compatibility exposing it as a global seems the best option.  I think it needs to be a reference set by the mapper function, may disguised as a function:
```ocaml
val get_mapper : unit -> mapper
(** [get_mapper ()] is the current deriving-mapper.  This must be called from a deriving plugin. *)
```
Any other suggestion?

**Comment by whitequark** [comment]
I think a (more) elegant solution would be moving Ppx_deriving_main.{derive,derive_type_decl,derive_type_ext,module_from_input_name,mapper} into Ppx_deriving. mapper would be just a field, since it's almost stateless*. Ppx_deriving_main would only consist of code that does plugin loading and maintaining the Ast_mapper cookie.

(*) It has implicit state in form of module_nesting. It could be tempting to make that state local to the mapper, but in fact it /should/ be global, since the whole compiler-libs are global, and I can't really envision using the mapper outside of a compiler-libs context. It has to rely on Location.input_name anyway.

**Comment by paurkedal** [comment]
I don't understand where you suggest where you suggest putting the mapper field.  The only record I can see is deriver, but that is constructed before the mapper.  We could create a new record, as I suggested, but how can we pass it to the deriver implementations without breaking backwards compatibility?

**Comment by whitequark** [comment]
Exporting it as `Ppx_deriving.mapper`. (Deriver plugins can't, or shouldn't even if they somehow can, directly refer to Ppx_deriving_main.

**Comment by paurkedal** [comment]
Aha, we're going for a global then. But it still needs to be a ref, since mapper is only defined after processing the arguments passed by PPX.  We can expose it as a function if you prefer, and then I see the need for moving the code from main.

**Comment by whitequark** [comment]
No, no need to be a ref. [This code](https://github.com/whitequark/ppx_deriving/blob/master/src/ppx_deriving_main.ml#L89-L91) is the only part that depends on argv, and it should be left in Ppx_deriving_main. It would process argv, then just return `Ppx_deriving.mapper`.

**Comment by paurkedal** [comment]
Aha, `registry` is mutable, so mapper can be constructed before loading the plugins.  I'll seen a PR shortly.

**Comment by paurkedal** [comment]
The local `structure` function uses `add_plugins`, so it seems I have to move pretty much all code to `Ppx_deriving`, leaving only
```ocaml
let mapper argv =
  get_plugins () |> List.iter dynlink;
  add_plugins argv;
  Ppx_deriving.mapper

let () =
  Ast_mapper.register "ppx_deriving" mapper
```
But then, do we wish to expose the plugin-related functions to the user, or do we move that code, as well?

BTW, any preference for where the `mapper` should be put in the interface?  I've put it at the bottom, and left out the other from the interface.

**Comment by paurkedal** [comment]
If it's okay to load the plugins before `Ppx_deriving_main.mapper` is called, then I'd move the `get_plugins () |> List.iter dynlink` to a module level init, which means the only plugin-related function we need to expose is `Ppx_deriving.add_plugins`.

Sorry you have to spell things out.  I'm just familiarising myself with PPX, using deriving as a soft introduction to the topic.

**Comment by whitequark** [comment]
`get_plugins ()` can't be moved into module level dynlink since it depends on Ast_mapper cookie being set, and it is only set after `Ast_mapper.register` starts executing.

Otherwise you pretty much nailed it in the previous comment.
