### ISSUE TITLE
doc should mention that show has to be used in the code for it to be usable from toplevel

### ISSUE THREAD

**Issue by unhammer** [whitequark/ppx_deriving#36]
I use deriving show just to make it easier to see stuff in utop, but when I compile the code, it doesn't seem to get applied unless I refer to the show function somewhere in the code. Perhaps the README should mention this, since it may be a bit confusing to newcomers.

**Comment by whitequark** [comment]
Can you explain what exactly your issue is? I do not understand it.

**Comment by unhammer** [comment]
OK, this might be a PEBKAC; I was going to make a minimal test case here but now I can't reproduce it any longer. Sorry for the noise …
