### ISSUE TITLE
Object support ?

### ISSUE THREAD

**Issue by vbmithr** [whitequark/ppx_deriving#37]
Not sure how this would actually work, but it would be nice to have at least a pretty printer for object via ppx_deriving.

**Comment by whitequark** [comment]
What should it print?

**Comment by vbmithr** [comment]
I was thinking about this in the context of having object serving as "views" of data. The object would be equivalent to a record, but instead of having fields, it would have method that would return meaningful data from raw data.
I'm looking for a way to display C datastructures. Currently, I use cstruct to autogenerate the code to access the C structure fields. I'd like to also be able to display them. I was thinking of using an object for that, that would have one method per C structure field, that would get the data (using cstruct) when called.

If I could serialize this object as a string, where each method would be called to obtain the thing to print, then this would be very useful for me.

**Comment by whitequark** [comment]
Can you implement this using `[@printer]`? If yes, how? If not, why?

**Comment by vbmithr** [comment]
On 15/06/2015 09:10, whitequark wrote:
> Can you implement this using |[@printer]|? If yes, how? If not, why?

I have not taken the time to understand how the "show" function works,
but if it is possible to derive a show function from a object that
would, for each method of type () -> some type, print this some type,
this would certainly work.

The problem is that in the general case, an object can have method of
any type, that should be printed as <abstract>/<opaque>.


-- 
Vincent

**Comment by whitequark** [comment]
Uh, no. ppx_deriving_show will not call every method that accepts `()`, that would just invoke side effects where you don't expect it.

**Comment by vbmithr** [comment]
On 15/06/2015 09:42, whitequark wrote:
> Uh, no. ppx_deriving_show will not call every method that accepts |()|,
> that would just invoke side effects where you don't expect it.

Right, this is not generic.
I'm looking for a way to construct "views" of data in OCaml in general,
not sure how I should do this.

But, thanks :)

-- 
Vincent

**Comment by whitequark** [comment]
You could do your own ppx_deriving plugin that would do this to object types, then use it to construct printers for ppx_deriving_show.

**Comment by vbmithr** [comment]
Ok, thanks!
