### ISSUE TITLE
ocamlfind ocamldep dependencies

### ISSUE THREAD

**Issue by braibant** [whitequark/ppx_deriving#38]
I have some trouble understanding what looks like an issue with the ppx_deriving ocamlfind package.

`ocamlfind ocamldep  -package X ... -package Z -modules myfile.mli` outputs a proper list of depencides, e.g., 

```
myfile.mli:  Format Hex  Z
```

while 

`ocamlfind ocamldep  -package X ... -package Z -package ppx_deriving  -modules myfile.mli` produces an empty dependency list for `myfile.mli`. 

Would you have any idea about what's going on?

**Comment by whitequark** [comment]
Most likely there is some kind of error encountered by ppx_deriving. Unfortunately the process to extract that from ocamldep is contrived. Can you try replacing ocamldep with ocamlc and see if it compiles?

**Comment by braibant** [comment]
Oh you are right. I have a `Cannot locate deriver <local deriver here>` error using `ocamlc`. Which points to a now-obvious mistake in our  `myocamlbuild.ml` plugin...

Thanks a lot.
