### ISSUE TITLE
regression with 4.02.2 regarding attributes

### ISSUE THREAD

**Issue by c-cube** [whitequark/ppx_deriving#39]
Looks like attributes are ignored in 4.02.2:

```ocaml
#require "ppx_deriving.show";;
type foo = { bar : int [@opaque] } ;;
show_foo {bar=1};;
```

expect: `{ bar = <opaque>"}`
got: `{ bar = 1 }`

**Comment by whitequark** [comment]
Yeah, the code above now looks like `type foo = { bar [@opaque] : int }`. Can you please make a PR?

**Comment by c-cube** [comment]
I will, tomorrow. I assume you mean that the attribute is attached to the field label, rather than the field type.

**Comment by whitequark** [comment]
Exactly. I have asked for this change, in fact.

**Comment by c-cube** [comment]
I'm not exactly sure how to proceed. Apparently, the previous design (attaching attributes to types) allowed to use `expr_of_typ` on the type. Now, in the case of a record field, I would have to either duplicate attribute detection in `expr_of_type` for records, or give the field attributes to `expr_of_typ`…

**Comment by vbmithr** [comment]
```
utop # type foo = { bar [@opaque] : int } [@@deriving show];;                                                                      
Error: Syntax error
```

It's me, or ?

**Comment by whitequark** [comment]
Not you. In 4.02.2, the attribute can't be placed after record field name to avoid ambiguity. The attribute after the type goes into its slot instead. (Think of it as moving the attribute from `{ bar * : int }` to `{ bar : int * }`.

**Comment by whitequark** [comment]
@c-cube Can you detect the attribute in expr_of_type for records and attach it back to the record type so that dependent code does not have to change or distinguish these cases?
