### ISSUE TITLE
2.1 doesn't work with OCaml 4.02.1 + merlin - update opam to reflect this

### ISSUE THREAD

**Issue by hcarty** [whitequark/ppx_deriving#42]
The opam package for 2.1 should probably be constrained to OCaml >= 4.02.2

**Comment by hcarty** [comment]
I'll submit the change to ocaml/opam-repository if you agree.

**Comment by whitequark** [comment]
Sure.

**Comment by whitequark** [comment]
Have you ever submitted this change?

**Comment by whitequark** [comment]
@hcarty Ping?

**Comment by whitequark** [comment]
Done.
