### ISSUE TITLE
Compiler-libs Btype.hash_variant

### ISSUE THREAD

**Issue by db4** [whitequark/ppx_deriving#51]
Sometimes it's convenient to serialize a polymorphic variant using it's hash value. Unfortunately `Btype.hash_variant` is not accessible from a `ppx_deriving` plugin. And I cannot dynload `ocamlcommon.cma` because it uses unsafe features. Do you know the way to calculate hash value without copy&paste from `btype.ml`?

**Comment by whitequark** [comment]
There isn't. (Except `Obj.magic`, but that's even worse.)

**Comment by whitequark** [comment]
Wish granted: https://github.com/whitequark/ppx_deriving/commit/7e21e335a80f27c2fcaaf8bacac66dcab3759484.
