### ISSUE TITLE
MinGW build failure

### ISSUE THREAD

**Issue by camlspotter** [whitequark/ppx_deriving#54]
With MinGW OCaml, the build command `ocaml pkg/build.ml native=true native-dynlink=true` fails as follows:

```
Solver failed:
  Ocamlbuild knows of no rules that apply to a target named src/ppx_deriving.lib. This can happen if you ask Ocamlbuild to build a target with the wrong extension (e.g. .opt instead of .native) or if the source files live in directories that have not been specified as include directories.
Backtrace:
  - Failed to build the target src/ppx_deriving.lib
      - Building src/ppx_deriving.lib
```

I guess this is since MinGW OCaml uses a cross compiler for MinGW which produces library files with `*.a` instead of `*.lib`.  The following quick but not entirely correct patch againnst `topkg.ml` fixed the issue: 

```
--- a/pkg/topkg.ml
+++ b/pkg/topkg.ml
@@ -152,7 +152,7 @@ end
 module Exts : Exts = struct
   let interface = [".mli"; ".cmi"; ".cmti"]
   let interface_opt = ".cmx" :: interface
-  let c_library = if Sys.win32 then [".lib"] else [".a"]
+  let c_library = [".a"]
   let c_dll_library = if Sys.win32 then [".dll"] else [".so"]
   let library = [".cma"; ".cmxa"; ".cmxs"] @ c_library
   let module_library = (interface_opt @ library)
```

To fix the issue properly, I guess you need to find which C compiler OCaml actually executes.

**Comment by whitequark** [comment]
Known bug: https://github.com/dbuenzli/topkg/issues/11

**Comment by camlspotter** [comment]
I got the workaround above so I am ok for myself.  Please close the ticket if you like.  Thanks!
