### ISSUE TITLE
Shouldn't "create" be "make"?

### ISSUE THREAD

**Issue by darioteixeira** [whitequark/ppx_deriving#62]
This may be an exercise in bikeshedding, but naming constructors `make` seems to be a more common practice.  Is there a particular reason why ppx_deriving chose `create`?

**Comment by whitequark** [comment]
`Array.create` etc

**Comment by darioteixeira** [comment]
> `Array.create` etc

Which is precisely my point: `Array.create` is deprecated in favour of `Array.make`...

**Comment by whitequark** [comment]
Hm. I don't remember.

**Comment by whitequark** [comment]
Would you write a PR adding `make` as an alias to `create` and emitting a deprecation warning?

**Comment by darioteixeira** [comment]
Sure.  I'll try to find some time for it...

**Comment by whitequark** [comment]
This is fixed by #66.
