### ISSUE TITLE
Compatibility of Ppx_deriving_runtime.Pervasives with Pervasives inside Merlin

### ISSUE THREAD

**Issue by sapristi** [whitequark/ppx_deriving#63]
When doing `print_string (show_qsqdsqd dqsd)`, merlin says `Error: This expression has type Ppx_deriving_runtime.string but an expression was expected of type string`, although the code compiles and runs well.

**Comment by whitequark** [comment]
I think that's a bug in Merlin.

**Comment by whitequark** [comment]
Bug reported upstream.
