### ISSUE TITLE
Why does ppx_deriving.create always has a `unit` at the end?

### ISSUE THREAD

**Issue by rgrinberg** [whitequark/ppx_deriving#65]
for example:

```
type point = { x: float ; y: float } [@@deriving create]

val create : x:float -> y:float -> unit -> point
```

I thought the `unit` is only necessary if any of the labels have a default value? (i.e. optional).

**Comment by whitequark** [comment]
True, but I didn't implement that for reason that I am unable to remember. That would be a breaking change... worth it?

**Comment by rgrinberg** [comment]
I'm against breaking people's code if there's a bunch of usage in the wild. No idea whether that's the case however.

Another possibility is to have `[@@deriving make]` that will not generate the extra `unit` when it's not necessary. Might address #62 as well? This would be satisfactory to me.

**Comment by whitequark** [comment]
Sure. Would you prepare a PR?

**Comment by rgrinberg** [comment]
Sure, I'll give it a try. First, let me try fixing `create` outright to see if there was anything concrete that stopped you.

**Comment by whitequark** [comment]
I've already looked, there's nothing in particular, it just doesn't have the check for optionals. Should be easy enough to fix

**Comment by rgrinberg** [comment]
@whitequark I think we can close this. Can we expect a release in the near future?

**Comment by whitequark** [comment]
3.1 released opam publish submit ./ppx_deriving.3.1
