### ISSUE TITLE
Question: How to run ppx_deriving with ppx_deriving using a particular plugin:

### ISSUE THREAD

**Issue by rgrinberg** [whitequark/ppx_deriving#70]
Citing your blog post http://whitequark.org/blog/2014/04/16/a-guide-to-extension-points-in-ocaml/ it should be something like this:

```
$ ocamlfind ppx_tools/rewriter ./ppx_deriving_main.native test.ml
```

But I'm not sure where to pass the names of concrete plugins. For example `ppx_deriving.eq`

**Comment by whitequark** [comment]
Uhm.
```
$ ocamlfind ppx_tools/rewriter -ppx "ocamlfind ppx_deriving/ppx_deriving $(ocamlfind query -predicates ppx_driver,byte -format '%d/%a' ppx_deriving.show)"
type a = int [@@deriving show];;
type a = int[@@deriving show]
let rec pp_a : Format.formatter -> a -> Ppx_deriving_runtime.unit=
   in
  ((let open! Ppx_deriving_runtime in fun fmt  -> Format.fprintf fmt "%d")
    [@ocaml.warning "-A"])
and show_a : a -> Ppx_deriving_runtime.string=
  fun x  -> Format.asprintf "%a" pp_a x
```

**Comment by rgrinberg** [comment]
Thanks @whitequark , at least I don't feel bad for asking because I definitely wouldn't have figured that out on my own.

Perhaps it's worth a mention in the README.

**Comment by whitequark** [comment]
Mhm, not sure. It's a gross solution.

**Comment by whitequark** [comment]
Meh, `ocaml -dsource` is a far better solution.

**Comment by whitequark** [comment]
README updated.
