### ISSUE TITLE
"show cannot be derived for int" for records

### ISSUE THREAD

**Issue by dariusf** [whitequark/ppx_deriving#73]
I'm playing around with @camlspotter's [TyPPX library](https://bitbucket.org/camlspotter/typpx). With a ppx preprocessor that depends on TyPPX (an identity mapper is sufficient to reproduce this) and ppx_deriving in the same project, I get `show cannot be derived for int` for records:

```ocaml
type a = { b : int }
  [@@deriving show]
```

Strangely, this
```ocaml
type c = int
  [@@deriving show]
```
compiles and works fine.

**Comment by camlspotter** [comment]
I feel this is not a problem of ppx_deriving.

Could you make a repro case *with build scripts*? Combining two PPXs can be very sensitive with their application order therefore I need the exact build commands you tried.

You can also use TyPPX issue page I have created at 
https://bitbucket.org/camlspotter/typpx/issues?status=new&status=open

**Comment by dariusf** [comment]
Sure, I'll repost this over at BitBucket. Thanks!
