### ISSUE TITLE
Change Arg to use Result

### ISSUE THREAD

**Issue by rgrinberg** [whitequark/ppx_deriving#75]
There's no need for the

```ocaml
[`Ok of 'a | `Error of string]
```

polymorphic variant as `result` is available in 4.03 and as a findlib packages for earlier OCaml's.

Is there anyway to make this transition without breaking a bunch of code?

**Comment by whitequark** [comment]
What benefit does it have?

**Comment by Drup** [comment]
Interop, avoiding poly variants (and the associated bad error messages).

**Comment by c-cube** [comment]
This is going to break every package that uses `ppx_deriving` (also, `ppx_deriving_yojson`). I don't think we have a clear idea of how to transition from this error type to `Result` yet in any OCaml project…

**Comment by whitequark** [comment]
Yes, this needs a major version bump.

**Comment by rgrinberg** [comment]
For me the benefit is that I can use standard result combinators (such as using dbuenzli's rresult).

But I think the breakage is being overestimated perhaps. This change would only break other derivers. Of which there's only several of:

A rough estimate of those was done using `$ opam list --depends-on ppx_deriving --all | grep -i ppx | grep -v deprecated | grep -iv 113` which attempts to remove non ppx and JSC packages (since those only export to ppx_deriving's api and not really use it).

Here's what I get:

```
ppx_deriving_morphism        0.1  Morphism generator for OCaml >=4.02
ppx_deriving_protobuf        2.2  A Protocol Buffers codec generator for OCaml >
ppx_deriving_yojson          2.4  JSON codec generator for OCaml >=4.02
ppx_json_types               0.2  JSON type providers
ppx_meta_conv              2.2.0  ppx_meta_conv, ppx based type_conv for various
```

Seems manageable. Pinging those maintainers to see what their thoughts about this breaking change is @camlspotter @nv-vn @choeger

**Comment by c-cube** [comment]
I think the switch to result needs to happen, but it *will* break user code too. For instance I sometimes pattern-match directly the result of `foo_of_yojson`.

**Comment by rgrinberg** [comment]
@c-cube Hmm but I consider ppx_deriving_yojson's return types a yojson issue that is orthogonal to this. This issue can be addressed without touching ppx_deriving_yojson's generated code.

**Comment by c-cube** [comment]
you would keep ``[`Ok | `Error]`` in ppx_deriving_yojson but not in ppx_deriving? sounds weird... (Just to be clear, there are explicit error types in the code generated by `ppx_deriving_yojson`, for deserialization)

**Comment by rgrinberg** [comment]
I'm in favor of changing `ppx_deriving_yojson` as well but I don't yet have an idea how much churning it on opam.

**Comment by nv-vn** [comment]
Personally, I'm in favor of the change here. Since the only packages depending on `ppx_deriving` are other `ppx`s, it's quite likely that those maintainers will have to change their code just to get it to work with changes to 4.03's AST (constants are being changed, for example, which is a breaking change), so I don't think it's too much to ask for if I'm going to be rewriting code to accommodate for different changes anyways.

**Comment by camlspotter** [comment]
I am ok if you want the change.  Please increase the minor version so that I can notice when you would have done it. :-)
