### ISSUE TITLE
Missing implementation Ppx_deriving_runtime

### ISSUE THREAD

**Issue by olleharstedt** [whitequark/ppx_deriving#89]
I get the error message in title when I try to binary compile my program using ppx_deriving.3.3. Any idea why? (Using opam; fresh installation; ocaml 4.02.2.)

**Comment by whitequark** [comment]
Succeeds over here. Can you show the full build log, with -verbose passed to ocamlfind?

**Comment by olleharstedt** [comment]
Build log of ppx_deriving or my program?

**Comment by whitequark** [comment]
Latter.

**Comment by olleharstedt** [comment]
Now idea how to copy-paste from VirtualBox command-line, but here's a screen-shot: http://imgur.com/PZr5a1M

Is this the information you need?

**Comment by whitequark** [comment]
Use `-linkpkg` instead, or in addition to, `-linkall`

**Comment by olleharstedt** [comment]
That worked, thank you!
