### ISSUE TITLE
This expression has type Ppx_deriving_runtime.string, expected string

### ISSUE THREAD

**Issue by olleharstedt** [whitequark/ppx_deriving#90]
Another error message. Help?

**Comment by olleharstedt** [comment]
Using ppx_deriving.3.3

**Comment by whitequark** [comment]
That's a bug in your tooling. `Ppx_deriving_runtime.string` is the same as `string`: https://github.com/whitequark/ppx_deriving/blob/master/src/ppx_deriving_runtime.mli#L29.

Are you using Merlin? I know Merlin sometimes does this.

**Comment by olleharstedt** [comment]
No Merlin.

**Comment by olleharstedt** [comment]
https://github.com/olleharstedt/subsetphp/blob/master/llvm_test.ml#L96

**Comment by whitequark** [comment]
Please make a minimal repro and submit as an OCaml bug.

**Comment by olleharstedt** [comment]
OK.

**Comment by olleharstedt** [comment]
Found the error: Had forgotten to include `-package ppx_deriving` in the last makefile line. Unexpected error message, though, should have been a link error...

**Comment by whitequark** [comment]
Just use ocamlbuild... makefiles aren't worth the debugging time.
